-- Create saved_articles table if it doesn't exist
create table if not exists public.saved_articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  url text not null,
  title text,
  excerpt text,
  image_url text,
  source text,
  content text,
  unique(user_id, url)
);

-- Set up Row Level Security (RLS)
alter table public.saved_articles enable row level security;

-- Create policies
create policy "Users can view their own saved articles"
  on public.saved_articles for select
  using (auth.uid() = user_id);

create policy "Users can insert their own saved articles"
  on public.saved_articles for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own saved articles"
  on public.saved_articles for delete
  using (auth.uid() = user_id);
